apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-client
  namespace: default
  labels:
    app: k8s-api-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-client
  template:
    metadata:
      labels:
        app: k8s-api-client
    spec:
      serviceAccountName: k8s-api-client
      containers:
      - name: k8s-api-client
        image: localhost/k8s-api-client:latest
        imagePullPolicy: Never  # For local KinD testing
        env:
        - name: TARGET_NAMESPACE
          value: "default"
        # Downward API: Pod metadata
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
